---
- hosts: all
  gather_facts: true
  vars:
      credentials:                                                              
        - ansible-some-credentials   
        - ansible-ssh-key
  tasks:
    - name: create a Job Template                               
      ansible.controller.job_template:                                                         
        name: job                                                                 
        description: description                                                  
        organization: Org Name                                                        
        tower_host: "{{ tower_host }}"                                         
        tower_username: "admin"                                                   
        tower_password: "{{ tower_password }}"                                                  
        job_type: "run"                                                           
        inventory: "Test inventory"                                               
        project: "Provisioning"                                                   
        playbook: "createjob_template.yml"                                              
        verbosity: 4                                                              
        credentials: 
          - ansible-some-credentials   
          - ansible-ssh-key
        state: "present"                                                          
        validate_certs: no
